Update matrix

diff --git a/CS344/matrix b/CS344/matrix
--- a/CS344/matrix
+++ b/CS344/matrix
@@ -107,24 +107,14 @@ add(){
 			# Iterate vertically
 			for ((j=0; j < $n1_cols; j++)); do 
 				# Iterate horizontally
-
-				if [ $n1_cols != $n2_cols ]; then
-					# Correction for the narrower matrix
-					# Row = 2* Rounded((curr row) + (curr col)/(n_cols))
-					# Col = (curr col) % half of n_cols
-					
-					# Determine which matrix is wider
-					if [ $n1_cols -lt $n2_cols ]; then
-						printf "m1 narrower\n"
-						
-					elif [ $n1_cols -gt $n2_cols ]; then
-						printf "m2 narrower\n"
-						
-					fi
+				if [ $n1_cols != $n2_cols ] || [ $n1_rows != $n2_rows ]; then
+					printf "Error: Matrices unmatched. Invalid operation.\n" >&2
+					exit 1
 				else
-					# Correction not needed
-					cur_elem=$((${m1[$i]:$j:1} + ${m2[$i]:$j:1}))
-					printf " "
+					# They match. Add
+					A=${m1[$i]:$j:1}
+					B=${m2[$i]:$j:1}
+					cur_elem=$((A + B))
 				fi
 				
 				# Prints the combined element				
@@ -132,7 +122,7 @@ add(){
 				if [ $j != "0" ]; then
 					printf "\t"
 				fi
-				printf "${m1[$n_elem]}, n_elem = $n_elem\n"
+				printf "$cur_elem"
 			done
 			# Print new lines between the transposed rows
 			printf "\nROW COMPLETE\n"
