Update matrix

diff --git a/CS344/matrix b/CS344/matrix
--- a/CS344/matrix
+++ b/CS344/matrix
@@ -148,9 +148,16 @@ multiply(){
         m2+=("$row") # Store each row of matrix 2 in an array as a string
     done < "$2"
 	
-	# Check columns of m1 == rows of m2
+	# Check columns of m1 != rows of m2
 	
-	# Do the multiplucation
+	if [[ (n1_cols = n2_rows) ]]; then
+		printf "Error: Matrices are incompatible.\n" >&2
+		exit 1
+	else 
+		# Do the multiplucation
+		printf "Multiplying matrices. \n"
+	fi
+
 }
 #####################################################################
 # Main script
