Update matrix

diff --git a/CS344/matrix b/CS344/matrix
--- a/CS344/matrix
+++ b/CS344/matrix
@@ -84,14 +84,11 @@ add(){
 	n2_rows=$(cat $2 | wc -l)
 	n2_cols=$(awk '{print NF}' $2 | sort -nu | tail -n 1)
 	
-	if [n1_rows != n2_rows] || [n1_cols != n2_cols]; then
-		# Dimensions are not the same
-		if [n1_rows != n2_cols] || [n1_cols != n2_rows]; then
-			# Dimensions are not mirrored
-			printf "Error: Matrices unmatched. Invalid operation.\n" >&2
-			exit 1
-		fi
-		# Else, dimensions are mirrored: valid
+	if [n1_rows != n2_rows] || [n1_cols != n2_cols]
+	&& [n1_rows != n2_cols] || [n1_cols != n2_rows]; then
+		# Dimensions are not identical, and not mirrored
+		printf "Error: Matrices unmatched. Invalid operation.\n" >&2
+		exit 1
 	else 
 		# Dimensions are the same: valid
 		
@@ -102,7 +99,7 @@ add(){
 			
 				# Iterate horizontally
 				# Adds a tab between elements
-				if [ $i != "0"]; then
+				if [ $i != "0" ]; then
 					printf "\t"
 				fi
 				
