Testing cleaning up code for add()

diff --git a/CS344/matrix b/CS344/matrix
--- a/CS344/matrix
+++ b/CS344/matrix
@@ -103,17 +103,17 @@ add(){
 			# Iterate vertically
 			for ((j=0; j < $n1_cols; j++)); do 
 				# Iterate horizontally
-				if [ $n1_cols != $n2_cols ] || [ $n1_rows != $n2_rows ]; then
-					printf "Error: Matrices unmatched. Invalid operation.\n" >&2
-					exit 1
-				else
+				# if [ $n1_cols != $n2_cols ] || [ $n1_rows != $n2_rows ]; then
+				# 	printf "Error: Matrices unmatched. Invalid operation.\n" >&2
+				# 	exit 1
+				# else
 					# They match.
 					a_line=(${m1[$i]})
 					b_line=(${m2[$i]})
 					a_num=${a_line[$j]}
 					b_num=${b_line[$j]}
 					cur_elem=$((a_num + b_num))
-				fi
+				# fi
 				
 				# Prints the combined element				
 				# Adds a tab between elements
@@ -130,8 +130,8 @@ add(){
 }
 
 #	multiply()	Multiplies two matrices
-# # Input:	Two matrices with the same dimesions
-# #	Output: One matrix with the dimesions of the first matrix
+# # Input:	Two matrices with dimensions MxN and NxP
+# #	Output: One matrix with the dimesions MxP
 multiply(){
 	n1_rows=$(cat $1 | wc -l)
 	n1_cols=$(( $(cat $1 | wc -w)/(n1_rows) ))
@@ -154,8 +154,13 @@ multiply(){
 		printf "Error: Matrices are incompatible.\n" >&2
 		exit 1
 	else 
-		# Do the multiplucation
+		# Do the multiplication
 		printf "Multiplying matrices. \n"
+		
+		# Loop to multiply elements in row[i] of A by col[i] of B
+		
+		
+		
 	fi
 
 }
